version: "3.8"
name: spotijam-api
services:
  server:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
    ports:
      - "8080:8080"
      - "3000:3000" # websocket
      - "9229:9229" # for debugger
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"